# setup
setup: scan

# Loss
criterion: scan
criterion_kwargs:
   entropy_weight: 5.0

# Model
backbone: resnet50

# Weight update
update_cluster_head_only: True # Train only linear layer during SCAN
num_heads: 10 # Use multiple heads

# Dataset
train_db_name: rico_20
val_db_name: rico20
num_classes: 20
num_neighbors: 20 

# Transformations
augmentation_strategy: ours 
augmentation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
   num_strong_augs: 4
   cutout_kwargs:
     n_holes: 1
     length: 16
     random: True

transformation_kwargs:
   crop_size: 32
   normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]

# Hyperparameters
optimizer: adam
optimizer_kwargs:
   lr: 0.0001
   weight_decay: 0.0001
epochs: 50
batch_size: 128
num_workers: 8

# Scheduler
scheduler: constant