#setup 
setup: simclr

#model 
backbone: resnet18
model_kwargs:
   head: mlp
   features_dim: 128 

#dataset
train_db_name: rico_20
val_db_name: rico_20 
num_classes: 21

# Loss
criterion: simclr
criterion_kwargs:
   temperature: 0.1 

# Hyperparameters
epochs: 1000
optimizer: sgd
optimizer_kwargs:
   nesterov: False
   weight_decay: 0.0001 
   momentum: 0.9
   lr: 0.4
scheduler: cosine
scheduler_kwargs:
   lr_decay_rate: 0.1
batch_size: 128 
num_workers: 8 # changed from 8 to not have to deal with data -- went back and dealt with data divisible by 8

#test augment ours
augmentation_strategy: simclr
# Transformations
augmentation_kwargs:
   random_resized_crop:
      size: 96
      scale: [0.2, 1.0]
   color_jitter_random_apply:
      p: 0.8
   color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
   random_grayscale: 
      p: 0.2
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

transformation_kwargs:
   crop_size: 96
   normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]